DEFINE_ACTION_FUNCTION ~DSOAL~ BEGIN

COPY ~bg2improvedgui/dsoal/files/alsoft.ini~        ~alsoft.ini~
COPY ~bg2improvedgui/dsoal/files/dsoal-aldrv.dll~   ~dsoal-aldrv.dll~
COPY ~bg2improvedgui/dsoal/files/dsoal-dsound.dll~  ~dsoal-dsound.dll~

COPY "TobEx_ini/TobExTweak.ini" "TobEx_ini/TobExTweak.ini"
        APPEND_FILE "bg2improvedgui/dsoal/files/TobEx_ini.txt"
BUT_ONLY


END  //DEFINE_ACTION_FUNCTION
